In [1]:
# only for cuda enabled laptop and desktop
import tensorflow as tf
physical_devices = tf.config.experimental.list_physical_devices('GPU')
print(physical_devices)
if physical_devices:
  tf.config.experimental.set_memory_growth(physical_devices[0], True)

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

In [3]:
from sklearn.datasets import load_boston

In [4]:
data = load_boston()

In [5]:
data

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [6]:
dataset = pd.DataFrame(data.data,columns=data.feature_names)

In [7]:
dataset['price'] = data.target

In [8]:
dataset

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  price  
0       15.3  396.90   4.98   24.0  
1       17.8  396.90   9.14   21.6  
2       17.8  392.83   4.03   34.7  
3       18.7  394.63   2.94   33.4  
4       18.7  396.90   5.33   36.2  
..       ...     ...    ...    ...  
501     21.0  391.99   9.67   22.4  
502     21.0  396.90   9.08   20.6  
503     21.0  396.90   5.64   23.9  
504     21.0  393.45   6.48   22.0  
505     21.0  396.90   7.88   11.9  

[506 rows x 14 columns]

In [9]:
X = dataset.iloc[:,0:13].values

In [10]:
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [11]:
y = dataset.iloc[:,13].values

In [12]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()

In [15]:
X = scaler.fit_transform(X)

In [16]:
X

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [17]:
X.shape

(506, 13)

In [18]:
from keras.models import Sequential
from keras.layers import Dense
import keras

In [19]:
model = Sequential()

In [20]:
model.add(Dense(100,activation='relu',input_dim=13))
model.add(Dense(50,activation='relu'))
model.add(Dense(20,activation='relu'))
model.add(Dense(1))

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               1400      
_________________________________________________________________
dense_1 (Dense)              (None, 50)                5050      
_________________________________________________________________
dense_2 (Dense)              (None, 20)                1020      
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 21        
Total params: 7,491
Trainable params: 7,491
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.compile(loss='mean_squared_error',optimizer='adam')

In [ ]:
model.fit(X,y,epochs=1500)

Epoch 1/1500
16/16 [==============================] - 3s 5ms/step - loss: 580.2297
Epoch 2/1500
16/16 [==============================] - 0s 3ms/step - loss: 514.6373
Epoch 3/1500
16/16 [==============================] - 0s 3ms/step - loss: 386.8235
Epoch 4/1500
16/16 [==============================] - 0s 3ms/step - loss: 189.0952
Epoch 5/1500
16/16 [==============================] - 0s 3ms/step - loss: 71.2486
Epoch 6/1500
16/16 [==============================] - 0s 3ms/step - loss: 47.6875
Epoch 7/1500
16/16 [==============================] - 0s 4ms/step - loss: 32.0598
Epoch 8/1500
16/16 [==============================] - 0s 3ms/step - loss: 26.2209
Epoch 9/1500
16/16 [==============================] - 0s 3ms/step - loss: 23.1369
Epoch 10/1500
16/16 [==============================] - 0s 3ms/step - loss: 20.9316
Epoch 11/1500
16/16 [==============================] - 0s 3ms/step - loss: 19.4137
Epoch 12/1500
16/16 [==============================] - 0s 3ms/step - loss: 18.2117
Epoch 13/

16/16 [==============================] - 0s 3ms/step - loss: 4.4867
Epoch 101/1500
16/16 [==============================] - 0s 2ms/step - loss: 4.5488
Epoch 102/1500
16/16 [==============================] - 0s 3ms/step - loss: 4.2988
Epoch 103/1500
16/16 [==============================] - 0s 2ms/step - loss: 4.3837
Epoch 104/1500
16/16 [==============================] - 0s 2ms/step - loss: 4.4298
Epoch 105/1500
16/16 [==============================] - 0s 2ms/step - loss: 4.0716
Epoch 106/1500
16/16 [==============================] - 0s 2ms/step - loss: 4.1380
Epoch 107/1500
16/16 [==============================] - 0s 2ms/step - loss: 4.1245
Epoch 108/1500
16/16 [==============================] - 0s 2ms/step - loss: 4.1162
Epoch 109/1500
16/16 [==============================] - 0s 2ms/step - loss: 4.1164
Epoch 110/1500
16/16 [==============================] - 0s 3ms/step - loss: 3.9243
Epoch 111/1500
16/16 [==============================] - 0s 3ms/step - loss: 3.9325
Epoch 112/1500
16/1

16/16 [==============================] - 0s 2ms/step - loss: 2.0955
Epoch 199/1500
16/16 [==============================] - 0s 2ms/step - loss: 2.0745
Epoch 200/1500
16/16 [==============================] - 0s 2ms/step - loss: 2.0198
Epoch 201/1500
16/16 [==============================] - 0s 2ms/step - loss: 2.0944
Epoch 202/1500
16/16 [==============================] - 0s 2ms/step - loss: 1.9786
Epoch 203/1500
16/16 [==============================] - 0s 3ms/step - loss: 2.0455
Epoch 204/1500
16/16 [==============================] - 0s 3ms/step - loss: 2.0496
Epoch 205/1500
16/16 [==============================] - 0s 3ms/step - loss: 2.1669
Epoch 206/1500
16/16 [==============================] - 0s 3ms/step - loss: 2.1311
Epoch 207/1500
16/16 [==============================] - 0s 3ms/step - loss: 2.0717
Epoch 208/1500
16/16 [==============================] - 0s 2ms/step - loss: 2.0654
Epoch 209/1500
16/16 [==============================] - 0s 2ms/step - loss: 2.1911
Epoch 210/1500
16/1

16/16 [==============================] - 0s 2ms/step - loss: 1.2410
Epoch 297/1500
16/16 [==============================] - 0s 2ms/step - loss: 1.3101
Epoch 298/1500
16/16 [==============================] - 0s 2ms/step - loss: 1.2276
Epoch 299/1500
16/16 [==============================] - 0s 2ms/step - loss: 1.1098
Epoch 300/1500
16/16 [==============================] - 0s 2ms/step - loss: 1.0692
Epoch 301/1500
16/16 [==============================] - 0s 3ms/step - loss: 1.1316
Epoch 302/1500
16/16 [==============================] - 0s 2ms/step - loss: 1.1443
Epoch 303/1500
16/16 [==============================] - 0s 2ms/step - loss: 1.1343
Epoch 304/1500
16/16 [==============================] - 0s 3ms/step - loss: 1.0380
Epoch 305/1500
16/16 [==============================] - 0s 2ms/step - loss: 1.0640
Epoch 306/1500
16/16 [==============================] - 0s 2ms/step - loss: 1.0436
Epoch 307/1500
16/16 [==============================] - 0s 2ms/step - loss: 1.1047
Epoch 308/1500
16/1